sudo: required

language: generic
services:
  - docker
jobs:
  include:
    - stage: Check restart of docker container
      script:
        - docker build -t onlyoffice-documentserver .
        - docker run -itd --name onlyoffice-documentserver onlyoffice/documentserver:5.0.7.38
        - sleep 1m # for init of services
        - docker restart onlyoffice-documentserver
        - sleep 1m # for init of services
        - if [[ $(docker exec onlyoffice-documentserver cat /var/log/rabbitmq/startup_err | wc -c) -ne 0 ]]; then exit 1; fi
